/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.AdminConversationsInviteErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for AdminConversationsInviteErrorSchemaException type.
 */
public class AdminConversationsInviteErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 6313061412270285897L;
    private AdminConversationsInviteErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public AdminConversationsInviteErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the AdminConversationsInviteErrorEnum
     */
    @JsonGetter("error")
    public AdminConversationsInviteErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for AdminConversationsInviteErrorEnum
     */
    @JsonSetter("error")
    private void setError(AdminConversationsInviteErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this AdminConversationsInviteErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminConversationsInviteErrorSchemaException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", error=" + error + ", ok=" + ok + "]";
    }
}
