/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.AdminConversationsUnarchiveErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for AdminConversationsUnarchiveErrorSchema3Exception type.
 */
public class AdminConversationsUnarchiveErrorSchema3Exception extends ApiException {
    private static final long serialVersionUID = -5850040192186643744L;
    private AdminConversationsUnarchiveErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public AdminConversationsUnarchiveErrorSchema3Exception(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the AdminConversationsUnarchiveErrorEnum
     */
    @JsonGetter("error")
    public AdminConversationsUnarchiveErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for AdminConversationsUnarchiveErrorEnum
     */
    @JsonSetter("error")
    private void setError(AdminConversationsUnarchiveErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this AdminConversationsUnarchiveErrorSchema3Exception into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminConversationsUnarchiveErrorSchema3Exception [" + "statusCode="
                + getResponseCode() + ", message=" + getMessage() + ", error=" + error + ", ok="
                + ok + "]";
    }
}
