/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.AdminConversationsSetConversationPrefsErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for AdminConversationsSetConversationPrefsErrorSchemaException type.
 */
public class AdminConversationsSetConversationPrefsErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 6407142004449951753L;
    private AdminConversationsSetConversationPrefsErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public AdminConversationsSetConversationPrefsErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the AdminConversationsSetConversationPrefsErrorEnum
     */
    @JsonGetter("error")
    public AdminConversationsSetConversationPrefsErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for AdminConversationsSetConversationPrefsErrorEnum
     */
    @JsonSetter("error")
    private void setError(AdminConversationsSetConversationPrefsErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this AdminConversationsSetConversationPrefsErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminConversationsSetConversationPrefsErrorSchemaException [" + "statusCode="
                + getResponseCode() + ", message=" + getMessage() + ", error=" + error + ", ok="
                + ok + "]";
    }
}
