/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.AdminConversationsArchiveErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for AdminConversationsArchiveErrorSchemaException type.
 */
public class AdminConversationsArchiveErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 805105653788632761L;
    private AdminConversationsArchiveErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public AdminConversationsArchiveErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the AdminConversationsArchiveErrorEnum
     */
    @JsonGetter("error")
    public AdminConversationsArchiveErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for AdminConversationsArchiveErrorEnum
     */
    @JsonSetter("error")
    private void setError(AdminConversationsArchiveErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this AdminConversationsArchiveErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminConversationsArchiveErrorSchemaException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", error=" + error + ", ok=" + ok + "]";
    }
}
