/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.AdminConversationsGetTeamsErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for AdminConversationsGetTeamsErrorSchemaException type.
 */
public class AdminConversationsGetTeamsErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 5307653198568693161L;
    private AdminConversationsGetTeamsErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public AdminConversationsGetTeamsErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the AdminConversationsGetTeamsErrorEnum
     */
    @JsonGetter("error")
    public AdminConversationsGetTeamsErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for AdminConversationsGetTeamsErrorEnum
     */
    @JsonSetter("error")
    private void setError(AdminConversationsGetTeamsErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this AdminConversationsGetTeamsErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminConversationsGetTeamsErrorSchemaException [" + "statusCode="
                + getResponseCode() + ", message=" + getMessage() + ", error=" + error + ", ok="
                + ok + "]";
    }
}
