/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.ConversationsKickErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for ConversationsKickErrorSchemaException type.
 */
public class ConversationsKickErrorSchemaException extends ApiException {
    private static final long serialVersionUID = -7272990276944253840L;
    private String callstack;
    private ConversationsKickErrorEnum error;
    private String needed;
    private String ok;
    private String provided;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public ConversationsKickErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @return Returns the String
     */
    @JsonGetter("callstack")
    public String getCallstack() {
        return this.callstack;
    }

    /**
     * Setter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @param callstack Value for String
     */
    @JsonSetter("callstack")
    private void setCallstack(String callstack) {
        this.callstack = callstack;
    }

    /**
     * Getter for Error.
     * @return Returns the ConversationsKickErrorEnum
     */
    @JsonGetter("error")
    public ConversationsKickErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for ConversationsKickErrorEnum
     */
    @JsonSetter("error")
    private void setError(ConversationsKickErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Needed.
     * @return Returns the String
     */
    @JsonGetter("needed")
    public String getNeeded() {
        return this.needed;
    }

    /**
     * Setter for Needed.
     * @param needed Value for String
     */
    @JsonSetter("needed")
    private void setNeeded(String needed) {
        this.needed = needed;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Provided.
     * @return Returns the String
     */
    @JsonGetter("provided")
    public String getProvided() {
        return this.provided;
    }

    /**
     * Setter for Provided.
     * @param provided Value for String
     */
    @JsonSetter("provided")
    private void setProvided(String provided) {
        this.provided = provided;
    }

    /**
     * Converts this ConversationsKickErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConversationsKickErrorSchemaException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", callstack=" + callstack + ", error=" + error
                + ", needed=" + needed + ", ok=" + ok + ", provided=" + provided + "]";
    }
}
