/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.PinsAddErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for PinsAddErrorSchemaException type.
 */
public class PinsAddErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 4087585799989347744L;
    private String callstack;
    private PinsAddErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public PinsAddErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @return Returns the String
     */
    @JsonGetter("callstack")
    public String getCallstack() {
        return this.callstack;
    }

    /**
     * Setter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @param callstack Value for String
     */
    @JsonSetter("callstack")
    private void setCallstack(String callstack) {
        this.callstack = callstack;
    }

    /**
     * Getter for Error.
     * @return Returns the PinsAddErrorEnum
     */
    @JsonGetter("error")
    public PinsAddErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for PinsAddErrorEnum
     */
    @JsonSetter("error")
    private void setError(PinsAddErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this PinsAddErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PinsAddErrorSchemaException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", callstack=" + callstack + ", error=" + error + ", ok=" + ok
                + "]";
    }
}
