/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.UsersInfoErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for UsersInfoErrorSchemaException type.
 */
public class UsersInfoErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 8037342094973618432L;
    private String callstack;
    private UsersInfoErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public UsersInfoErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Callstack.
     * @return Returns the String
     */
    @JsonGetter("callstack")
    public String getCallstack() {
        return this.callstack;
    }

    /**
     * Setter for Callstack.
     * @param callstack Value for String
     */
    @JsonSetter("callstack")
    private void setCallstack(String callstack) {
        this.callstack = callstack;
    }

    /**
     * Getter for Error.
     * @return Returns the UsersInfoErrorEnum
     */
    @JsonGetter("error")
    public UsersInfoErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for UsersInfoErrorEnum
     */
    @JsonSetter("error")
    private void setError(UsersInfoErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this UsersInfoErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsersInfoErrorSchemaException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", callstack=" + callstack + ", error=" + error + ", ok=" + ok
                + "]";
    }
}
