/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.slack.models.UsersProfileSetErrorEnum;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for UsersProfileSetErrorSchemaException type.
 */
public class UsersProfileSetErrorSchemaException extends ApiException {
    private static final long serialVersionUID = 998188169688346548L;
    private String callstack;
    private UsersProfileSetErrorEnum error;
    private String ok;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public UsersProfileSetErrorSchemaException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @return Returns the String
     */
    @JsonGetter("callstack")
    public String getCallstack() {
        return this.callstack;
    }

    /**
     * Setter for Callstack.
     * Note: PHP callstack is only visible in dev/qa
     * @param callstack Value for String
     */
    @JsonSetter("callstack")
    private void setCallstack(String callstack) {
        this.callstack = callstack;
    }

    /**
     * Getter for Error.
     * @return Returns the UsersProfileSetErrorEnum
     */
    @JsonGetter("error")
    public UsersProfileSetErrorEnum getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for UsersProfileSetErrorEnum
     */
    @JsonSetter("error")
    private void setError(UsersProfileSetErrorEnum error) {
        this.error = error;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return this.ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Converts this UsersProfileSetErrorSchemaException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsersProfileSetErrorSchemaException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", callstack=" + callstack + ", error=" + error
                + ", ok=" + ok + "]";
    }
}
