/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AdminConversationsGetConversationPrefsErrorEnum to be used.
 */
public enum AdminConversationsGetConversationPrefsErrorEnum {
    FEATURE_NOT_ENABLED,

    NOT_AN_ADMIN,

    NOT_AN_ENTERPRISE,

    RESTRICTED_ACTION,

    MISSING_SCOPE,

    CHANNEL_NOT_FOUND,

    CHANNEL_TYPE_NOT_SUPPORTED,

    COULD_NOT_GET_CONVERSATION_PREFS;


    private static TreeMap<String, AdminConversationsGetConversationPrefsErrorEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        NOT_AN_ADMIN.value = "not_an_admin";
        NOT_AN_ENTERPRISE.value = "not_an_enterprise";
        RESTRICTED_ACTION.value = "restricted_action";
        MISSING_SCOPE.value = "missing_scope";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        CHANNEL_TYPE_NOT_SUPPORTED.value = "channel_type_not_supported";
        COULD_NOT_GET_CONVERSATION_PREFS.value = "could_not_get_conversation_prefs";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("not_an_admin", NOT_AN_ADMIN);
        valueMap.put("not_an_enterprise", NOT_AN_ENTERPRISE);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("missing_scope", MISSING_SCOPE);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("channel_type_not_supported", CHANNEL_TYPE_NOT_SUPPORTED);
        valueMap.put("could_not_get_conversation_prefs", COULD_NOT_GET_CONVERSATION_PREFS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AdminConversationsGetConversationPrefsErrorEnum constructFromString(String toConvert) throws IOException {
        AdminConversationsGetConversationPrefsErrorEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AdminConversationsGetConversationPrefsErrorEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AdminConversationsGetConversationPrefsErrorEnum values to list of string values.
     * @param toConvert The list of AdminConversationsGetConversationPrefsErrorEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AdminConversationsGetConversationPrefsErrorEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AdminConversationsGetConversationPrefsErrorEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 