/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AdminConversationsDeleteErrorEnum to be used.
 */
public enum AdminConversationsDeleteErrorEnum {
    FEATURE_NOT_ENABLED,

    NOT_AN_ADMIN,

    CHANNEL_NOT_FOUND,

    CHANNEL_TYPE_NOT_SUPPORTED,

    DEFAULT_ORG_WIDE_CHANNEL,

    RESTRICTED_ACTION,

    COULD_NOT_DELETE_CHANNEL,

    MISSING_SCOPE;


    private static TreeMap<String, AdminConversationsDeleteErrorEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        NOT_AN_ADMIN.value = "not_an_admin";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        CHANNEL_TYPE_NOT_SUPPORTED.value = "channel_type_not_supported";
        DEFAULT_ORG_WIDE_CHANNEL.value = "default_org_wide_channel";
        RESTRICTED_ACTION.value = "restricted_action";
        COULD_NOT_DELETE_CHANNEL.value = "could_not_delete_channel";
        MISSING_SCOPE.value = "missing_scope";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("not_an_admin", NOT_AN_ADMIN);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("channel_type_not_supported", CHANNEL_TYPE_NOT_SUPPORTED);
        valueMap.put("default_org_wide_channel", DEFAULT_ORG_WIDE_CHANNEL);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("could_not_delete_channel", COULD_NOT_DELETE_CHANNEL);
        valueMap.put("missing_scope", MISSING_SCOPE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AdminConversationsDeleteErrorEnum constructFromString(String toConvert) throws IOException {
        AdminConversationsDeleteErrorEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AdminConversationsDeleteErrorEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AdminConversationsDeleteErrorEnum values to list of string values.
     * @param toConvert The list of AdminConversationsDeleteErrorEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AdminConversationsDeleteErrorEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AdminConversationsDeleteErrorEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 