/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AdminConversationsGetTeamsErrorEnum to be used.
 */
public enum AdminConversationsGetTeamsErrorEnum {
    FEATURE_NOT_ENABLED,

    CHANNEL_NOT_FOUND,

    CHANNEL_TYPE_NOT_SUPPORTED,

    UNSUPPORTED_TEAM_TYPE,

    RESTRICTED_ACTION,

    COULD_NOT_GET_TEAMS,

    INVALID_CURSOR,

    INVALID_LIMIT;


    private static TreeMap<String, AdminConversationsGetTeamsErrorEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        CHANNEL_TYPE_NOT_SUPPORTED.value = "channel_type_not_supported";
        UNSUPPORTED_TEAM_TYPE.value = "unsupported_team_type";
        RESTRICTED_ACTION.value = "restricted_action";
        COULD_NOT_GET_TEAMS.value = "could_not_get_teams";
        INVALID_CURSOR.value = "invalid_cursor";
        INVALID_LIMIT.value = "invalid_limit";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("channel_type_not_supported", CHANNEL_TYPE_NOT_SUPPORTED);
        valueMap.put("unsupported_team_type", UNSUPPORTED_TEAM_TYPE);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("could_not_get_teams", COULD_NOT_GET_TEAMS);
        valueMap.put("invalid_cursor", INVALID_CURSOR);
        valueMap.put("invalid_limit", INVALID_LIMIT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AdminConversationsGetTeamsErrorEnum constructFromString(String toConvert) throws IOException {
        AdminConversationsGetTeamsErrorEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AdminConversationsGetTeamsErrorEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AdminConversationsGetTeamsErrorEnum values to list of string values.
     * @param toConvert The list of AdminConversationsGetTeamsErrorEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AdminConversationsGetTeamsErrorEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AdminConversationsGetTeamsErrorEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 