/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AdminConversationsCreateErrorEnum to be used.
 */
public enum AdminConversationsCreateErrorEnum {
    FEATURE_NOT_ENABLED,

    NAME_TAKEN,

    RESTRICTED_ACTION,

    TEAM_NOT_FOUND,

    INVALID_TEAM,

    INVALID_NAME,

    COULD_NOT_CREATE_CHANNEL,

    TEAM_ID_OR_ORG_REQUIRED;


    private static TreeMap<String, AdminConversationsCreateErrorEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        NAME_TAKEN.value = "name_taken";
        RESTRICTED_ACTION.value = "restricted_action";
        TEAM_NOT_FOUND.value = "team_not_found";
        INVALID_TEAM.value = "invalid_team";
        INVALID_NAME.value = "invalid_name";
        COULD_NOT_CREATE_CHANNEL.value = "could_not_create_channel";
        TEAM_ID_OR_ORG_REQUIRED.value = "team_id_or_org_required";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("name_taken", NAME_TAKEN);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("team_not_found", TEAM_NOT_FOUND);
        valueMap.put("invalid_team", INVALID_TEAM);
        valueMap.put("invalid_name", INVALID_NAME);
        valueMap.put("could_not_create_channel", COULD_NOT_CREATE_CHANNEL);
        valueMap.put("team_id_or_org_required", TEAM_ID_OR_ORG_REQUIRED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AdminConversationsCreateErrorEnum constructFromString(String toConvert) throws IOException {
        AdminConversationsCreateErrorEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AdminConversationsCreateErrorEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AdminConversationsCreateErrorEnum values to list of string values.
     * @param toConvert The list of AdminConversationsCreateErrorEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AdminConversationsCreateErrorEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AdminConversationsCreateErrorEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 