/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TeamProfileGetErrorEnum to be used.
 */
public enum TeamProfileGetErrorEnum {
    NOT_AUTHED,

    INVALID_AUTH,

    ACCOUNT_INACTIVE,

    NO_PERMISSION,

    USER_IS_BOT,

    INVALID_ARG_NAME,

    INVALID_ARRAY_ARG,

    INVALID_CHARSET,

    INVALID_FORM_DATA,

    INVALID_POST_TYP,

    MISSING_POST_TYPE,

    TEAM_ADDED_TO_ORG,

    INVALID_JSON,

    JSON_NOT_OBJECT,

    REQUEST_TIMEOU,

    UPGRADE_REQUIRED;


    private static TreeMap<String, TeamProfileGetErrorEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        NOT_AUTHED.value = "not_authed";
        INVALID_AUTH.value = "invalid_auth";
        ACCOUNT_INACTIVE.value = "account_inactive";
        NO_PERMISSION.value = "no_permission";
        USER_IS_BOT.value = "user_is_bot";
        INVALID_ARG_NAME.value = "invalid_arg_name";
        INVALID_ARRAY_ARG.value = "invalid_array_arg";
        INVALID_CHARSET.value = "invalid_charset";
        INVALID_FORM_DATA.value = "invalid_form_data";
        INVALID_POST_TYP.value = "invalid_post_typ";
        MISSING_POST_TYPE.value = "missing_post_type";
        TEAM_ADDED_TO_ORG.value = "team_added_to_org";
        INVALID_JSON.value = "invalid_json";
        JSON_NOT_OBJECT.value = "json_not_object";
        REQUEST_TIMEOU.value = "request_timeou";
        UPGRADE_REQUIRED.value = "upgrade_required";

        valueMap.put("not_authed", NOT_AUTHED);
        valueMap.put("invalid_auth", INVALID_AUTH);
        valueMap.put("account_inactive", ACCOUNT_INACTIVE);
        valueMap.put("no_permission", NO_PERMISSION);
        valueMap.put("user_is_bot", USER_IS_BOT);
        valueMap.put("invalid_arg_name", INVALID_ARG_NAME);
        valueMap.put("invalid_array_arg", INVALID_ARRAY_ARG);
        valueMap.put("invalid_charset", INVALID_CHARSET);
        valueMap.put("invalid_form_data", INVALID_FORM_DATA);
        valueMap.put("invalid_post_typ", INVALID_POST_TYP);
        valueMap.put("missing_post_type", MISSING_POST_TYPE);
        valueMap.put("team_added_to_org", TEAM_ADDED_TO_ORG);
        valueMap.put("invalid_json", INVALID_JSON);
        valueMap.put("json_not_object", JSON_NOT_OBJECT);
        valueMap.put("request_timeou", REQUEST_TIMEOU);
        valueMap.put("upgrade_required", UPGRADE_REQUIRED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TeamProfileGetErrorEnum constructFromString(String toConvert) throws IOException {
        TeamProfileGetErrorEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TeamProfileGetErrorEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TeamProfileGetErrorEnum values to list of string values.
     * @param toConvert The list of TeamProfileGetErrorEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TeamProfileGetErrorEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TeamProfileGetErrorEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 