/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack;

import com.slack.apis.AdminAppsApi;
import com.slack.apis.AdminAppsApprovedApi;
import com.slack.apis.AdminAppsRequestsApi;
import com.slack.apis.AdminAppsRestrictedApi;
import com.slack.apis.AdminConversationsApi;
import com.slack.apis.AdminConversationsEkmApi;
import com.slack.apis.AdminConversationsRestrictAccessApi;
import com.slack.apis.AdminEmojiApi;
import com.slack.apis.AdminInviteRequestsApi;
import com.slack.apis.AdminInviteRequestsApprovedApi;
import com.slack.apis.AdminInviteRequestsDeniedApi;
import com.slack.apis.AdminTeamsAdminsApi;
import com.slack.apis.AdminTeamsApi;
import com.slack.apis.AdminTeamsOwnersApi;
import com.slack.apis.AdminTeamsSettingsApi;
import com.slack.apis.AdminUsergroupsApi;
import com.slack.apis.AdminUsersApi;
import com.slack.apis.AdminUsersSessionApi;
import com.slack.apis.Api;
import com.slack.apis.AppsApi;
import com.slack.apis.AppsEventAuthorizationsApi;
import com.slack.apis.AppsPermissionsApi;
import com.slack.apis.AppsPermissionsResourcesApi;
import com.slack.apis.AppsPermissionsScopesApi;
import com.slack.apis.AppsPermissionsUsersApi;
import com.slack.apis.AuthApi;
import com.slack.apis.BotsApi;
import com.slack.apis.CallsApi;
import com.slack.apis.CallsParticipantsApi;
import com.slack.apis.ChatApi;
import com.slack.apis.ChatScheduledMessagesApi;
import com.slack.apis.ConversationsApi;
import com.slack.apis.DialogApi;
import com.slack.apis.DndApi;
import com.slack.apis.EmojiApi;
import com.slack.apis.FilesApi;
import com.slack.apis.FilesCommentsApi;
import com.slack.apis.FilesRemoteApi;
import com.slack.apis.MigrationApi;
import com.slack.apis.OAuthAuthorizationApi;
import com.slack.apis.OauthApi;
import com.slack.apis.OauthV2Api;
import com.slack.apis.PinsApi;
import com.slack.apis.ReactionsApi;
import com.slack.apis.RemindersApi;
import com.slack.apis.RtmApi;
import com.slack.apis.SearchApi;
import com.slack.apis.StarsApi;
import com.slack.apis.TeamApi;
import com.slack.apis.TeamProfileApi;
import com.slack.apis.UsergroupsApi;
import com.slack.apis.UsergroupsUsersApi;
import com.slack.apis.UsersApi;
import com.slack.apis.UsersProfileApi;
import com.slack.apis.ViewsApi;
import com.slack.apis.WorkflowsApi;
import com.slack.authentication.AuthorizationCodeAuthManager;
import com.slack.authentication.AuthorizationCodeAuthModel;
import com.slack.http.client.HttpCallback;
import com.slack.http.client.HttpClientConfiguration;
import com.slack.http.client.ReadonlyHttpClientConfiguration;
import com.slack.logging.configuration.ApiLoggingConfiguration;
import com.slack.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class SlackWebApiClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private AdminAppsApi adminApps;
    private AdminAppsApprovedApi adminAppsApproved;
    private AdminAppsRequestsApi adminAppsRequests;
    private AdminAppsRestrictedApi adminAppsRestricted;
    private AdminConversationsApi adminConversations;
    private AdminConversationsEkmApi adminConversationsEkm;
    private AdminConversationsRestrictAccessApi adminConversationsRestrictAccess;
    private AdminEmojiApi adminEmoji;
    private AdminInviteRequestsApi adminInviteRequests;
    private AdminInviteRequestsApprovedApi adminInviteRequestsApproved;
    private AdminInviteRequestsDeniedApi adminInviteRequestsDenied;
    private AdminTeamsAdminsApi adminTeamsAdmins;
    private AdminTeamsApi adminTeams;
    private AdminTeamsOwnersApi adminTeamsOwners;
    private AdminTeamsSettingsApi adminTeamsSettings;
    private AdminUsergroupsApi adminUsergroups;
    private AdminUsersApi adminUsers;
    private AdminUsersSessionApi adminUsersSession;
    private Api api;
    private AppsEventAuthorizationsApi appsEventAuthorizations;
    private AppsPermissionsApi appsPermissions;
    private AppsPermissionsResourcesApi appsPermissionsResources;
    private AppsPermissionsScopesApi appsPermissionsScopes;
    private AppsPermissionsUsersApi appsPermissionsUsers;
    private AppsApi apps;
    private AuthApi auth;
    private BotsApi bots;
    private CallsApi calls;
    private CallsParticipantsApi callsParticipants;
    private ChatApi chat;
    private ChatScheduledMessagesApi chatScheduledMessages;
    private ConversationsApi conversations;
    private DialogApi dialog;
    private DndApi dnd;
    private EmojiApi emoji;
    private FilesCommentsApi filesComments;
    private FilesApi files;
    private FilesRemoteApi filesRemote;
    private MigrationApi migration;
    private OauthApi oauth;
    private OauthV2Api oauthV2;
    private PinsApi pins;
    private ReactionsApi reactions;
    private RemindersApi reminders;
    private RtmApi rtm;
    private SearchApi search;
    private StarsApi stars;
    private TeamApi team;
    private TeamProfileApi teamProfile;
    private UsergroupsApi usergroups;
    private UsergroupsUsersApi usergroupsUsers;
    private UsersApi users;
    private UsersProfileApi usersProfile;
    private ViewsApi views;
    private WorkflowsApi workflows;
    private OAuthAuthorizationApi oAuthAuthorization;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java-SDK/1.0.0 (OS: {os-info}, Engine: {engine}/{engine-version})";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * AuthorizationCodeAuthManager.
     */
    private AuthorizationCodeAuthManager authorizationCodeAuthManager;

    /**
     * The instance of AuthorizationCodeAuthModel.
     */
    private AuthorizationCodeAuthModel authorizationCodeAuthModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SlackWebApiClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig,
            AuthorizationCodeAuthModel authorizationCodeAuthModel, HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.authorizationCodeAuthModel = authorizationCodeAuthModel;

        this.authorizationCodeAuthManager = new AuthorizationCodeAuthManager(
                authorizationCodeAuthModel);
        this.authentications.put("slackAuth", authorizationCodeAuthManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        this.authorizationCodeAuthManager.applyGlobalConfiguration(globalConfig);

        adminApps = new AdminAppsApi(globalConfig);
        adminAppsApproved = new AdminAppsApprovedApi(globalConfig);
        adminAppsRequests = new AdminAppsRequestsApi(globalConfig);
        adminAppsRestricted = new AdminAppsRestrictedApi(globalConfig);
        adminConversations = new AdminConversationsApi(globalConfig);
        adminConversationsEkm = new AdminConversationsEkmApi(globalConfig);
        adminConversationsRestrictAccess = new AdminConversationsRestrictAccessApi(globalConfig);
        adminEmoji = new AdminEmojiApi(globalConfig);
        adminInviteRequests = new AdminInviteRequestsApi(globalConfig);
        adminInviteRequestsApproved = new AdminInviteRequestsApprovedApi(globalConfig);
        adminInviteRequestsDenied = new AdminInviteRequestsDeniedApi(globalConfig);
        adminTeamsAdmins = new AdminTeamsAdminsApi(globalConfig);
        adminTeams = new AdminTeamsApi(globalConfig);
        adminTeamsOwners = new AdminTeamsOwnersApi(globalConfig);
        adminTeamsSettings = new AdminTeamsSettingsApi(globalConfig);
        adminUsergroups = new AdminUsergroupsApi(globalConfig);
        adminUsers = new AdminUsersApi(globalConfig);
        adminUsersSession = new AdminUsersSessionApi(globalConfig);
        api = new Api(globalConfig);
        appsEventAuthorizations = new AppsEventAuthorizationsApi(globalConfig);
        appsPermissions = new AppsPermissionsApi(globalConfig);
        appsPermissionsResources = new AppsPermissionsResourcesApi(globalConfig);
        appsPermissionsScopes = new AppsPermissionsScopesApi(globalConfig);
        appsPermissionsUsers = new AppsPermissionsUsersApi(globalConfig);
        apps = new AppsApi(globalConfig);
        auth = new AuthApi(globalConfig);
        bots = new BotsApi(globalConfig);
        calls = new CallsApi(globalConfig);
        callsParticipants = new CallsParticipantsApi(globalConfig);
        chat = new ChatApi(globalConfig);
        chatScheduledMessages = new ChatScheduledMessagesApi(globalConfig);
        conversations = new ConversationsApi(globalConfig);
        dialog = new DialogApi(globalConfig);
        dnd = new DndApi(globalConfig);
        emoji = new EmojiApi(globalConfig);
        filesComments = new FilesCommentsApi(globalConfig);
        files = new FilesApi(globalConfig);
        filesRemote = new FilesRemoteApi(globalConfig);
        migration = new MigrationApi(globalConfig);
        oauth = new OauthApi(globalConfig);
        oauthV2 = new OauthV2Api(globalConfig);
        pins = new PinsApi(globalConfig);
        reactions = new ReactionsApi(globalConfig);
        reminders = new RemindersApi(globalConfig);
        rtm = new RtmApi(globalConfig);
        search = new SearchApi(globalConfig);
        stars = new StarsApi(globalConfig);
        team = new TeamApi(globalConfig);
        teamProfile = new TeamProfileApi(globalConfig);
        usergroups = new UsergroupsApi(globalConfig);
        usergroupsUsers = new UsergroupsUsersApi(globalConfig);
        users = new UsersApi(globalConfig);
        usersProfile = new UsersProfileApi(globalConfig);
        views = new ViewsApi(globalConfig);
        workflows = new WorkflowsApi(globalConfig);
        oAuthAuthorization = new OAuthAuthorizationApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of AdminAppsApi.
     * @return adminApps
     */
    public AdminAppsApi getAdminAppsApi() {
        return adminApps;
    }

    /**
     * Get the instance of AdminAppsApprovedApi.
     * @return adminAppsApproved
     */
    public AdminAppsApprovedApi getAdminAppsApprovedApi() {
        return adminAppsApproved;
    }

    /**
     * Get the instance of AdminAppsRequestsApi.
     * @return adminAppsRequests
     */
    public AdminAppsRequestsApi getAdminAppsRequestsApi() {
        return adminAppsRequests;
    }

    /**
     * Get the instance of AdminAppsRestrictedApi.
     * @return adminAppsRestricted
     */
    public AdminAppsRestrictedApi getAdminAppsRestrictedApi() {
        return adminAppsRestricted;
    }

    /**
     * Get the instance of AdminConversationsApi.
     * @return adminConversations
     */
    public AdminConversationsApi getAdminConversationsApi() {
        return adminConversations;
    }

    /**
     * Get the instance of AdminConversationsEkmApi.
     * @return adminConversationsEkm
     */
    public AdminConversationsEkmApi getAdminConversationsEkmApi() {
        return adminConversationsEkm;
    }

    /**
     * Get the instance of AdminConversationsRestrictAccessApi.
     * @return adminConversationsRestrictAccess
     */
    public AdminConversationsRestrictAccessApi getAdminConversationsRestrictAccessApi() {
        return adminConversationsRestrictAccess;
    }

    /**
     * Get the instance of AdminEmojiApi.
     * @return adminEmoji
     */
    public AdminEmojiApi getAdminEmojiApi() {
        return adminEmoji;
    }

    /**
     * Get the instance of AdminInviteRequestsApi.
     * @return adminInviteRequests
     */
    public AdminInviteRequestsApi getAdminInviteRequestsApi() {
        return adminInviteRequests;
    }

    /**
     * Get the instance of AdminInviteRequestsApprovedApi.
     * @return adminInviteRequestsApproved
     */
    public AdminInviteRequestsApprovedApi getAdminInviteRequestsApprovedApi() {
        return adminInviteRequestsApproved;
    }

    /**
     * Get the instance of AdminInviteRequestsDeniedApi.
     * @return adminInviteRequestsDenied
     */
    public AdminInviteRequestsDeniedApi getAdminInviteRequestsDeniedApi() {
        return adminInviteRequestsDenied;
    }

    /**
     * Get the instance of AdminTeamsAdminsApi.
     * @return adminTeamsAdmins
     */
    public AdminTeamsAdminsApi getAdminTeamsAdminsApi() {
        return adminTeamsAdmins;
    }

    /**
     * Get the instance of AdminTeamsApi.
     * @return adminTeams
     */
    public AdminTeamsApi getAdminTeamsApi() {
        return adminTeams;
    }

    /**
     * Get the instance of AdminTeamsOwnersApi.
     * @return adminTeamsOwners
     */
    public AdminTeamsOwnersApi getAdminTeamsOwnersApi() {
        return adminTeamsOwners;
    }

    /**
     * Get the instance of AdminTeamsSettingsApi.
     * @return adminTeamsSettings
     */
    public AdminTeamsSettingsApi getAdminTeamsSettingsApi() {
        return adminTeamsSettings;
    }

    /**
     * Get the instance of AdminUsergroupsApi.
     * @return adminUsergroups
     */
    public AdminUsergroupsApi getAdminUsergroupsApi() {
        return adminUsergroups;
    }

    /**
     * Get the instance of AdminUsersApi.
     * @return adminUsers
     */
    public AdminUsersApi getAdminUsersApi() {
        return adminUsers;
    }

    /**
     * Get the instance of AdminUsersSessionApi.
     * @return adminUsersSession
     */
    public AdminUsersSessionApi getAdminUsersSessionApi() {
        return adminUsersSession;
    }

    /**
     * Get the instance of Api.
     * @return api
     */
    public Api getApi() {
        return api;
    }

    /**
     * Get the instance of AppsEventAuthorizationsApi.
     * @return appsEventAuthorizations
     */
    public AppsEventAuthorizationsApi getAppsEventAuthorizationsApi() {
        return appsEventAuthorizations;
    }

    /**
     * Get the instance of AppsPermissionsApi.
     * @return appsPermissions
     */
    public AppsPermissionsApi getAppsPermissionsApi() {
        return appsPermissions;
    }

    /**
     * Get the instance of AppsPermissionsResourcesApi.
     * @return appsPermissionsResources
     */
    public AppsPermissionsResourcesApi getAppsPermissionsResourcesApi() {
        return appsPermissionsResources;
    }

    /**
     * Get the instance of AppsPermissionsScopesApi.
     * @return appsPermissionsScopes
     */
    public AppsPermissionsScopesApi getAppsPermissionsScopesApi() {
        return appsPermissionsScopes;
    }

    /**
     * Get the instance of AppsPermissionsUsersApi.
     * @return appsPermissionsUsers
     */
    public AppsPermissionsUsersApi getAppsPermissionsUsersApi() {
        return appsPermissionsUsers;
    }

    /**
     * Get the instance of AppsApi.
     * @return apps
     */
    public AppsApi getAppsApi() {
        return apps;
    }

    /**
     * Get the instance of AuthApi.
     * @return auth
     */
    public AuthApi getAuthApi() {
        return auth;
    }

    /**
     * Get the instance of BotsApi.
     * @return bots
     */
    public BotsApi getBotsApi() {
        return bots;
    }

    /**
     * Get the instance of CallsApi.
     * @return calls
     */
    public CallsApi getCallsApi() {
        return calls;
    }

    /**
     * Get the instance of CallsParticipantsApi.
     * @return callsParticipants
     */
    public CallsParticipantsApi getCallsParticipantsApi() {
        return callsParticipants;
    }

    /**
     * Get the instance of ChatApi.
     * @return chat
     */
    public ChatApi getChatApi() {
        return chat;
    }

    /**
     * Get the instance of ChatScheduledMessagesApi.
     * @return chatScheduledMessages
     */
    public ChatScheduledMessagesApi getChatScheduledMessagesApi() {
        return chatScheduledMessages;
    }

    /**
     * Get the instance of ConversationsApi.
     * @return conversations
     */
    public ConversationsApi getConversationsApi() {
        return conversations;
    }

    /**
     * Get the instance of DialogApi.
     * @return dialog
     */
    public DialogApi getDialogApi() {
        return dialog;
    }

    /**
     * Get the instance of DndApi.
     * @return dnd
     */
    public DndApi getDndApi() {
        return dnd;
    }

    /**
     * Get the instance of EmojiApi.
     * @return emoji
     */
    public EmojiApi getEmojiApi() {
        return emoji;
    }

    /**
     * Get the instance of FilesCommentsApi.
     * @return filesComments
     */
    public FilesCommentsApi getFilesCommentsApi() {
        return filesComments;
    }

    /**
     * Get the instance of FilesApi.
     * @return files
     */
    public FilesApi getFilesApi() {
        return files;
    }

    /**
     * Get the instance of FilesRemoteApi.
     * @return filesRemote
     */
    public FilesRemoteApi getFilesRemoteApi() {
        return filesRemote;
    }

    /**
     * Get the instance of MigrationApi.
     * @return migration
     */
    public MigrationApi getMigrationApi() {
        return migration;
    }

    /**
     * Get the instance of OauthApi.
     * @return oauth
     */
    public OauthApi getOauthApi() {
        return oauth;
    }

    /**
     * Get the instance of OauthV2Api.
     * @return oauthV2
     */
    public OauthV2Api getOauthV2Api() {
        return oauthV2;
    }

    /**
     * Get the instance of PinsApi.
     * @return pins
     */
    public PinsApi getPinsApi() {
        return pins;
    }

    /**
     * Get the instance of ReactionsApi.
     * @return reactions
     */
    public ReactionsApi getReactionsApi() {
        return reactions;
    }

    /**
     * Get the instance of RemindersApi.
     * @return reminders
     */
    public RemindersApi getRemindersApi() {
        return reminders;
    }

    /**
     * Get the instance of RtmApi.
     * @return rtm
     */
    public RtmApi getRtmApi() {
        return rtm;
    }

    /**
     * Get the instance of SearchApi.
     * @return search
     */
    public SearchApi getSearchApi() {
        return search;
    }

    /**
     * Get the instance of StarsApi.
     * @return stars
     */
    public StarsApi getStarsApi() {
        return stars;
    }

    /**
     * Get the instance of TeamApi.
     * @return team
     */
    public TeamApi getTeamApi() {
        return team;
    }

    /**
     * Get the instance of TeamProfileApi.
     * @return teamProfile
     */
    public TeamProfileApi getTeamProfileApi() {
        return teamProfile;
    }

    /**
     * Get the instance of UsergroupsApi.
     * @return usergroups
     */
    public UsergroupsApi getUsergroupsApi() {
        return usergroups;
    }

    /**
     * Get the instance of UsergroupsUsersApi.
     * @return usergroupsUsers
     */
    public UsergroupsUsersApi getUsergroupsUsersApi() {
        return usergroupsUsers;
    }

    /**
     * Get the instance of UsersApi.
     * @return users
     */
    public UsersApi getUsersApi() {
        return users;
    }

    /**
     * Get the instance of UsersProfileApi.
     * @return usersProfile
     */
    public UsersProfileApi getUsersProfileApi() {
        return usersProfile;
    }

    /**
     * Get the instance of ViewsApi.
     * @return views
     */
    public ViewsApi getViewsApi() {
        return views;
    }

    /**
     * Get the instance of WorkflowsApi.
     * @return workflows
     */
    public WorkflowsApi getWorkflowsApi() {
        return workflows;
    }

    /**
     * Get the instance of OAuthAuthorizationApi.
     * @return oAuthAuthorization
     */
    public OAuthAuthorizationApi getOAuthAuthorizationApi() {
        return oAuthAuthorization;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with AuthorizationCodeAuth.
     * @return authorizationCodeAuth
     */
    public AuthorizationCodeAuth getAuthorizationCodeAuth() {
        return authorizationCodeAuthManager;
    }

    /**
     * The auth credential model for AuthorizationCodeAuth.
     * @return the instance of AuthorizationCodeAuthModel
     */
    public AuthorizationCodeAuthModel getAuthorizationCodeAuthModel() {
        return authorizationCodeAuthModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://slack.com/api";
            }
            if (server.equals(Server.AUTH_SERVER)) {
                return "https://slack.com/oauth";
            }
        }
        return "https://slack.com/api";
    }

    /**
     * Converts this SlackWebApiClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SlackWebApiClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", loggingConfig=" + loggingConfig + ", authentications="
                + authentications + "]";
    }

    /**
     * Builds a new {@link SlackWebApiClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SlackWebApiClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.authorizationCodeAuth(getAuthorizationCodeAuthModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SlackWebApiClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private AuthorizationCodeAuthModel authorizationCodeAuthModel =
                new AuthorizationCodeAuthModel.Builder("", "", "").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for AuthorizationCodeAuth.
         * @param authorizationCodeAuthModel The instance of AuthorizationCodeAuthModel.
         * @return The current instance of builder.
         */
        public Builder authorizationCodeAuth(
                AuthorizationCodeAuthModel authorizationCodeAuthModel) {
            this.authorizationCodeAuthModel = authorizationCodeAuthModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new SlackWebApiClient object using the set fields.
         * @return SlackWebApiClient
         */
        public SlackWebApiClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SlackWebApiClient(environment, httpClient, httpClientConfig, loggingConfig,
                    authorizationCodeAuthModel, httpCallback);
        }
    }
}